climbing_tracker/urls.py
from django.contrib import admin
from django.urls import include,path
#from rest_framework import routers

#router = routers.DefaultRouter()
#router.register(r'sessions', views.SessionViewSet)

urlpatterns = [
    #path('', include(router.urls)),
    path('journal/', include('journal.urls'), name='journal'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

journal/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns

from . import views, api_views

app_name = 'journal'
urlpatterns = [
    path('', login_required(views.SessionsIndexView.as_view()), name='index'),
    path('<int:pk>/', views.SessionsDetailView.as_view(), name='detail'),
    path('add_session', views.add_session, name='add_session'),
    path('add_climb', views.add_climb, name='add_climb'),
    path('delete_climb', views.delete_climb, name='delete_climb'),
    path('<int:session_id>/rate', views.rate, name='rate_session'),
    path('<int:session_id>/add_partners', views.add_partner, name='add_partner'),
    path('sign_up/', views.sign_up, name="sign-up"),
    path('all_climbs', views.all_climbs, name='all_climbs'),
    path('dashboard', views.dashboard, name='dashboard'),

    path('api/sessions/', api_views.SessionList.as_view()),
    path('api/sessions/<int:pk>', api_views.SessionDetails.as_view()),
    path('api/climbs/', api_views.ClimbList.as_view()),
    path('api/users/', api_views.UserList.as_view()),
    path('api/users/<int:pk>/', api_views.UserDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

journal/models.py
import datetime

from django.db import models
from django.utils import timezone

class Grade(models.Model):
    label = models.CharField(max_length=10)
    weight = models.IntegerField()

    def __str__(self):
        return self.label

class Location(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey('auth.User', related_name='user_location', on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' by ' + str(self.owner)

class Session(models.Model):
    location = models.ForeignKey(Location, related_name='location', on_delete=models.CASCADE)
    date = models.DateTimeField('date of climb')
    rating = models.IntegerField(default=0)
    owner = models.ForeignKey('auth.User', related_name='user_sessions',on_delete=models.CASCADE)

    def was_recorded_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=5) <= self.date <= now

    def __str__(self):
        return self.location.name + " on " + str(self.date.date())

class SessionPartner(models.Model):
    session = models.ForeignKey(Session, related_name="partners", on_delete=models.CASCADE)
    displayName = models.CharField(max_length=50)

class Climb(models.Model):
    grade =  models.ForeignKey(Grade, on_delete=models.CASCADE)
    comments = models.CharField(max_length=250, default=None)
    rating = models.IntegerField(default=0)
    session = models.ForeignKey(Session, related_name='climbs', on_delete=models.CASCADE)
    owner = models.ForeignKey('auth.User', related_name='user_climbs',on_delete=models.CASCADE)
    climb_type = models.CharField(max_length=20, default="Flash")
    takes = models.IntegerField(default=0)

    def __str__(self):
        return str(self.grade) + " - " + self.comments + " : " + str(self.rating)
    

journal/views.py
'''
Views for climbing journal app
'''
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from .models import Session, Climb, Grade, SessionPartner, Location

# Django views
class SessionsIndexView(generic.ListView):
    '''
        Class based Index View for Sessions
    '''
    template_name = 'journal/index.html'
    context_object_name = 'latest_sessions'

    def get_queryset(self):
        """Return the last five climbing sessions"""
        return Session.objects.order_by('-date')[:5]
    
    def get_context_data(self, **kwargs):
        context = super(SessionsIndexView, self).get_context_data(**kwargs)
        sessions = Session.objects.order_by('-rating')
        context['best_session'] = {}
        if len(sessions) > 0:    
            context['best_session']['location'] = sessions[0].location
            context['best_session']['rating'] = sessions[0].rating

        context['locations'] = Location.objects.all()
        return context


class SessionsDetailView(generic.DetailView):
    model = Session
    template_name = 'journal/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(SessionsDetailView, self).get_context_data(**kwargs)
        # Add climbs related to this session
        session = Session.objects.get(id=self.kwargs['pk'])
        context['grades'] = Grade.objects.all()
        context['climbs'] = session.climbs.all()
        partners = session.partners.all()
        if partners != None:
            context['partners'] = partners
        else:
            context['partners'] = ""
        return context


def rate(request, session_id):
    session = get_object_or_404(Session, pk=session_id)

    rating = request.POST['rating']
    session.rating = rating
    session.save()

    return HttpResponseRedirect(reverse('journal:detail', args=(session.id,)))

def add_session(request):
    session = Session()

    request_location = request.POST['location']
    location = None
    try:
        location = Location.objects.get(name=request_location, owner=request.user)
    except Location.DoesNotExist:
        location = Location()
        location.name = request_location
        location.owner = request.user
        location.save()

    rating = request.POST['rating']
    date = request.POST['date']

    session.location = location
    session.rating = rating
    session.date = date
    session.owner_id = request.user.id 

    session.save()

    return HttpResponseRedirect(reverse('journal:detail', args=(session.id,)))

def add_partner(request, session_id):
    sessionPartner = SessionPartner()

    sessionPartner.session = get_object_or_404(Session, pk=session_id)
    sessionPartner.displayName = request.POST['displayName']

    sessionPartner.save()

    return HttpResponseRedirect(reverse('journal:detail', args=(sessionPartner.session.id,)))


def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, 'journal/index.html')
    context['form'] = form
    return render(request, 'registration/sign_up.html', context)

def add_climb(request):
    #TODO: validation on user and session
    climb = Climb()

    grade_label = request.POST['grade']
    climb.grade =  Grade.objects.get(label=grade_label)
    climb.comments = request.POST['comments']
    climb.rating = request.POST['rating']
    session_id = request.POST['session']
    climb.session = Session.objects.get(id=session_id)
    climb.owner_id = request.user.id
    climb.climb_type = request.POST['climb_type']
    climb.takes = request.POST['takes']

    climb.save()

    return HttpResponseRedirect(reverse('journal:detail', args=(climb.session_id,)))

def delete_climb(request):
    #TODO: validate permissions
    climb = Climb.objects.get(id=request.POST['climb_id'])
    climb.delete()

    return HttpResponseRedirect(reverse('journal:detail', args=(climb.session_id,)))

def all_climbs(request):
    context = {}
    return render(request, 'journal/all_climbs.html', context)

def dashboard(request):
    context = {}
    return render(request, 'journal/dashboard.html', context)

# Method based views
# def index(request):
#     latest_sessions = Session.objects.order_by('date')[:5]
#     context = { 'latest_sessions': latest_sessions }
#     return render(request, 'journal/index.html', context)

# def detail(request, session_id):
#     session = get_object_or_404(Session, pk=session_id)
#     return render(request, 'journal/detail.html', { 'session': session})

journal/templates/journal/all_climbs.html
{% extends "journal/base.html" %}
{% block content %}
<p>Not implemented</p>
{% endblock %}

journal/templates/journal/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <!-- AutcompleteJS -->
        <script src="{% static 'journal/autoComplete.js' %}"></script>
        <link rel="stylesheet" href="{% static 'journal/autoComplete.01.css' %}">
        <!-- Internal CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
        <title>Climbing Tracker</title>
    </head>

    <main>
        {% block menubar %}
        <div class="container-md">
            <nav class="navbar navbar-expand-md bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'journal/images/carabiner.png' %}" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
                        Climbing Tracker
                    </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'journal:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'journal:all_climbs' %}">All climbs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'journal:dashboard' %}">Dashboard</a>
                    </li>
                    </ul>
                </div>
                </div>
            </nav>
        </div>
        {% endblock %}

        {% block content %}
        {% endblock %}
    </main>
</html>

journal/templates/journal/dashboard.html
{% extends "journal/base.html" %}
{% block content %}
<p>Not implemented</p>
{% endblock %}

journal/templates/journal/detail.html
{% extends "journal/base.html" %}
{% block content %}
    <div class="container-md">
        <div class="row">
            <div class="col-sm-8"><h1>{{ session.location }}</h1></div>
            <div class="col-sm-4"><h2>{{ session.date|date:"D d M Y" }}</h2></div>
        </div>
        <hr \>
    </div>
    <div class="container-md">
        <div class="row">
            <div class="col-sm-8">
                <h3>Partners: 
                    {% for partner in partners.all %}
                        {{ partner.displayName }} 
                    {% endfor %}
                </h3>
                <form action="{% url 'journal:add_partner' session.id %}" method="post">
                    {% csrf_token %}
                    <input type="text" id="displayName" name="displayName">  
                    <input type="submit" value="Add">
                </form>
            </div>
            <div class="col-sm-2">
                <h3> Rating: {{ session.rating }} </h3>
            </div>
            <div class="col-sm-2">
                <form action="{% url 'journal:rate_session' session.id %}" method="post">
                    {% csrf_token %}
        
                    <input type="range" id="rating" name="rating" min="1" max="10" 
                            oninput="document.getElementById('ratingLabel').innerHTML = this.value;">
                    <em id="ratingLabel">{{ session.rating }}</em>
        
                    <input type="submit" value="Rate">
                </form>
            </div>
        </div>
        <div class="row">
            
        </div>
    </div>
    
    <div class="container-md">
        <h3>{{ climbs.all|length }} Climbs</h3>
        <div class="table-responsive-md">
            <table class="table table-striped table-sm">
                <colgroup> 
                    <col class="col-md-1">
                    <col class="col-md-1">
                    <col class="col-md-1">
                    <col class="col-md-1">
                    <col class="col-md-1">
                    <col class="col-md-6">
                </colgroup>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Grade</th>
                        <th>Type</th>
                        <th>Takes</th>
                        <th>Rating</th>
                        <th>Comments</th>
                    </tr>
                </thead>
                <tbody>
                {% for climb in climbs.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ climb.grade }}</td>
                        <td>{{ climb.climb_type }}</td>
                        <td>{{ climb.takes }}</td>
                        <td>{{ climb.rating }}</td>
                        <td>{{ climb.comments }}</td>
                        <td>
                            <form action="{% url 'journal:delete_climb' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="climb_id" name="climb_id" value="{{ climb.id }}">
                                <input type="hidden" id="session_id" name="session_id" value="{{ session.id }}">
                                <input type="submit" value="Delete">
                            </form>
                        </td>
                    <tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="container-md">
        <form id="add_climb" action="{% url 'journal:add_climb' %}" method="post">
            {% csrf_token %}
            <label for="grade">Grade</label>
            <select id="grade" name="grade" form="add_climb">
            {% for grade in grades.all %}
                <option value="{{ grade.label }}">{{ grade.label }}</option>
            {% endfor %}
            </select>
            <label for="climb_type">Type</label>
            <select id="climb_type" name="climb_type">
                <option value="Flash">Flash</option> 
                <option value="Redpoint">Redpoint</option>
                <option value="Dogged">Dogged</option>
                <option value="Failed">Failed</option>
            </select>
            <label for="rating">Rating</label>
            <select id="rating" name="rating" form="add_climb">
                <option value="1">1</option><option value="2">2</option><option value="3">3<option value="4">4</option><option value="5">5</option>
                <option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option>
            </select>
            <input type="hidden" id="session" name="session" value="{{ session.id }}">
            
            <label for="takes">Takes</label>
            <input type="number" id="takes" name="takes" min="0" value="0">
            <label for="comments">Comments</label>
            <input type="text" id="comments" name="comments">  
            <input type="submit" value="Add">
        </form>
        </div>
{% endblock %}

journal/templates/journal/index.html
{% extends "journal/base.html" %}
{% block content %}
<div class="container-md">
    <div class="flex-row">
        <h1>Climbing Tracker for {{user}}</h1>
    </div>
    
    <!-- Add session-->
    <div class="flex-row border border-dark rounded">
        <div class="d-sm-flex justify-content-center bg-secondary">
            <form action="{% url 'journal:add_session' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="flex-row bg-secondary">
                <label>Location</label>
                <input id="location" name="location" type="search" dir="ltr" spellcheck=false autocorrect="off" autocomplete="off" autocapitalize="off" maxlength="2048" tabindex="1">
            </div>
            <div class="flex-row bg-secondary">
                <label>Date</label>
                <input type="date" id="date" name="date">
            </div>
            <div class="flex-row bg-secondary">
                <label>Rating</label>
                <input type="rating" id="rating" name="rating">
            </div>
            <div class="flex-row bg-secondary">
                <div class="d-sm-flex justify-content-center">
                    <input type="submit" value="Add">
                </div>
            </div>
            </form>
        </div>
    </div>
    
    <div class="flex-row"><div class="p-2 bd-dark"></div></div>

    {% if latest_sessions %}
    <div class="d-flex bd-highlight">
        <div class="p-2 w-50 justify-content-center bg-secondary border border-dark rounded">
            <h2>Last session</h2>
            <div class="col">
                <a class="text-white" href={% url 'journal:detail' latest_sessions.0.id %}>{{ latest_sessions.0 }}</a></li>
            </div>
        </div>
        <div class="p-2 w-10"><div class="w-50"></div></div>
        <div class="p-2 w-50 justify-content-center bg-secondary border border-dark rounded">
            <h2>Best climb</h2>            
        </div>
    </div>

    <div class="flex-row"><div class="p-2 bd-dark"></div></div>

    <div class="d-flex bd-highlight">
        <div class="p-2 w-50 justify-content-center bg-secondary border border-dark rounded">
            <h2>Last month</h2>
            <ul>
            {% for session in latest_sessions %}
                <li><a class="text-white" href={% url 'journal:detail' session.id %}>{{ session }}</a></li>
            {% endfor %}
            </ul>
        </div>
        <div class="p-2 w-10"><div class="w-50"></div></div>
        <div class="p-2 w-50 justify-content-center bg-secondary border border-dark rounded">
            <h2>Best session</h2>            
            <p>{{ best_session.location }} @ {{ best_session.rating }}</p> 
        </div>
    </div>
    {% else %}
        <p>No sessions are available.</p>
    {% endif %}
</div>

<script>
    // Autocomplete   
    var config = {
        selector: "#location",
        placeHolder: "Locations",
        data: {
            src: ["Bpump", "Pump2"]
        },
        resultItem: {
            highlight: true,
        },
        events: {
            input: {
                focus() {
                    if (autoCompleteJS.input.value.length) autoCompleteJS.start();
                },
                selection(event) {
                    const feedback = event.detail;
                    autoCompleteJS.input.blur();
                    // Prepare User's Selected Value
                    const selection = feedback.selection.value;
                    // Replace Input value with the selected value
                    autoCompleteJS.input.value = selection;
                    // Console log autoComplete data feedback
                    console.log(feedback);
                },
            },
        },
        
    };
    const autoCompleteJS = new autoComplete(config);
    
</script> 

{% endblock %}